version: '3.8'
services:
    redis:
        image: redis:6-alpine
        restart: "unless-stopped"
        environment:
            REDIS_HOST: ${REDIS__HOST}
            VOLUMES_DIR: ${VOLUMES_DIR}
        volumes:
            - "~/${VOLUMES_DIR}/redis-config:/usr/local/etc/redis"
            - "~/${VOLUMES_DIR}/redis-data:/data"
        ports:
            - "6379:6379"
        command: "redis-server /usr/local/etc/redis/redis.conf"
    db:
        image: postgres:14-alpine
        restart: "unless-stopped"
        environment:
            POSTGRES_USER: ${DB__USER}
            POSTGRES_PASSWORD: ${DB__PASSWORD}
            POSTGRES_DB: ${DB__NAME}
            VOLUMES_DIR: ${VOLUMES_DIR}
        volumes:
            - "~/${VOLUMES_DIR}/pg-data:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
