version: '3.8'
services:
    redis:
        image: redis:6-alpine
        restart: "unless-stopped"
        environment:
            REDIS_HOST: ${REDIS__HOST}
            VOLUMES_DIR: ${VOLUMES_DIR}
        volumes:
            - "~/${VOLUMES_DIR}/redis-config:/usr/local/etc/redis"
            - "~/${VOLUMES_DIR}/redis-data:/data"
        ports:
            - "16379:6379"
        command: "redis-server /usr/local/etc/redis/redis.conf"
    db:
        image: postgres:14-alpine
        restart: "unless-stopped"
        environment:
            POSTGRES_USER: ${DB__USER}
            POSTGRES_PASSWORD: ${DB__PASSWORD}
            POSTGRES_DB: ${DB__NAME}
            VOLUMES_DIR: ${VOLUMES_DIR}
        volumes:
            - "~/${VOLUMES_DIR}/pg-data:/var/lib/postgresql/data"
            - "~/${VOLUMES_DIR}/backups:/backups"
        ports:
            - "15432:5432"
        healthcheck:
            test: "exit 0"
    db_migration:
        build:
            context: .
        restart: "on-failure"
        depends_on:
            - db
        env_file: .env
        command: ["/wait-for-it/wait-for-it.sh", "db:5432", "-t", "2", "--", "python", "-m", "alembic", "upgrade", "head"]
    dbbackup:
        image: prodrigestivill/postgres-backup-local:14-alpine
        restart: always

        volumes:
            -   "~/${VOLUMES_DIR}/backups:/backups"
        links:
            -   db
        depends_on:
            db:
                condition: service_healthy
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_DB=${DB__NAME}
            - POSTGRES_USER=${DB__USER}
            - POSTGRES_PASSWORD=${DB__PASSWORD}
            - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
            - SCHEDULE=@daily
            - HEALTHCHECK_PORT=8080
    bot:
        build:
            context: .
        stop_signal: SIGINT
        restart: "unless-stopped"
        env_file: .env
        depends_on:
            - db
            - db_migration
            - redis
