"""add order, market, order_messages

Revision ID: 49c3975e57e6
Revises: 65ee8401cea8
Create Date: 2022-06-07 13:54:31.597940

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "49c3975e57e6"
down_revision = "65ee8401cea8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goods",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("type", sa.Enum("GOODS", "FOLDER", name="goodstype"), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("sku", sa.TEXT(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["goods.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "market",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("creator_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("recipient_market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("commentary", sa.TEXT(), nullable=False),
        sa.Column(
            "confirmed",
            sa.Enum("YES", "NO", "NOT_PROCESSED", name="confirmedstatus"),
            server_default="NOT_PROCESSED",
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["user.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["recipient_market_id"],
            ["market.id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_line",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("goods_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("quantity", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goods_id"], ["goods.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_message",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("message_id", sa.INTEGER(), nullable=False),
        sa.Column("chat_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_message")
    op.drop_table("order_line")
    op.drop_table("order")
    op.drop_table("market")
    op.drop_table("goods")
    # ### end Alembic commands ###
