"""order_creator_id_bigint

Revision ID: 9dfdf7059df2
Revises: eb19178d8727
Create Date: 2023-01-27 09:34:00.493830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import BIGINT

# revision identifiers, used by Alembic.
revision = '9dfdf7059df2'
down_revision = 'eb19178d8727'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column("order", "creator_id", type_=BIGINT)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
