"""unique market name

Revision ID: eb19178d8727
Revises: c82ae5449675
Create Date: 2022-06-21 19:21:40.720952

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb19178d8727"
down_revision = "c82ae5449675"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_market_name"), "market", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_market_name"), "market", type_="unique")
    # ### end Alembic commands ###
