"""add market, order, order_lines

Revision ID: f0ad6cd8beb0
Revises: d3767a5d75fc
Create Date: 2022-06-02 14:46:56.615300

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f0ad6cd8beb0"
down_revision = "d3767a5d75fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("creator_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("recipient_market_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("commentary", sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["user.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["recipient_market_id"],
            ["market.id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_line",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("goods_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("quantity", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goods_id"], ["goods.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_line")
    op.drop_table("order")
    op.drop_table("market")
    # ### end Alembic commands ###
