"""init

Revision ID: 65ee8401cea8
Revises: 
Create Date: 2022-05-30 14:09:33.890269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import orm

from app.config import load_config
from app.domain.access_levels.models.access_level import AccessLevel, LevelName
from app.domain.user.models.user import TelegramUser

revision = "65ee8401cea8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_level",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "BLOCKED", "USER", "ADMINISTRATOR", "CONFIRMATION", name="levelname"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_access_levels_table",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("access_level_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_level_id"],
            ["access_level.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "access_level_id"),
    )

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    blocked = AccessLevel(id=-1, name=LevelName.BLOCKED)
    admin = AccessLevel(id=1, name=LevelName.ADMINISTRATOR)
    user = AccessLevel(id=2, name=LevelName.USER)
    confirmation = AccessLevel(id=3, name=LevelName.CONFIRMATION)

    config = load_config()
    admins = [
        TelegramUser(
            id=admin_id, name="Admin", access_levels=[admin, user, confirmation]
        )
        for admin_id in config.tg_bot.admin_ids
    ]

    session.add_all(
        (
            blocked,
            admin,
            user,
            confirmation,
            *admins,
        )
    )

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_access_levels_table")
    op.drop_table("user")
    op.drop_table("access_level")
    # ### end Alembic commands ###
